name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        frontend: [true]
        backend: [true]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js for Vue.js (Frontend)
      if: matrix.frontend == true
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Frontend Dependencies and Build
      if: matrix.frontend == true
      run: |
        cd frontend
        npm install
        npm run build

    - name: Set up Go for Backend
      if: matrix.backend == true
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Build Backend (Golang)
      if: matrix.backend == true
      run: |
        cd backend
        go mod tidy
        go build -o myapp .

    - name: Run Tests (Frontend & Backend)
      run: |
        cd frontend && npm run test
        cd ../backend && go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Production (example using Docker)
      run: |
        docker-compose up -d --build